const skills = [
    "Jamovi",
    ".NET",
    "3ds Max",
    "Ableton Live",
    "Accounting",
    "Acting Audition",
    "Acting technique",
    "Adobe After Effects",
    "Adobe Audition",
    "Adobe Creative Suite",
    "Adobe Dreamweaver",
    "Adobe Fireworks",
    "Adobe Flash",
    "Adobe Illustrator",
    "Adobe Indesign",
    "Adobe Photoshop",
    "Adobe Photoshop Lightroom CC",
    "Adobe Premiere Pro",
    "Adobe XD",
    "Advanced Excel",
    "AJAX",
    "Algorithms",
    "Allegro Software",
    "Amazon Web Server (AWS)",
    "Amazon Web Services (AWS)",
    "American English",
    "Analog And Digital Circuits",
    "Anchoring",
    "Android",
    "Angular 2.0",
    "Angular 7.0",
    "AngularJS",
    "Animation",
    "ANSA",
    "Ansible",
    "ANSYS",
    "Apache",
    "Apache Cassandra",
    "Apache CloudStack",
    "Apache Kafka ",
    "Apex",
    "APIs",
    "Arabic Proficiency (Spoken)",
    "Arabic Proficiency (Written)",
    "ArcGIS",
    "Arduino",
    "ARM Microcontroller",
    "Articulate 360",
    "Articulate Storyline",
    "Artificial intelligence",
    "ASP.NET",
    "Assamese Proficiency (Spoken)",
    "Assamese Proficiency (Written)",
    "Atmel AVR",
    "Audacity",
    "Audio Editing",
    "Audio Making",
    "Audiology",
    "AutoCAD",
    "Autodesk 123D design",
    "Autodesk Alias",
    "Autodesk CFD",
    "Autodesk Fusion 360",
    "Autodesk Inventor",
    "Autodesk Maya",
    "Autodesk Moldflow",
    "Autodesk Mudbox",
    "Autodesk Revit",
    "Autodesk SketchBook",
    "Backbone.js",
    "Bar bending schedule\/Schedule of bars",
    "Bash",
    "Bengali Proficiency (Spoken)",
    "Bengali Proficiency (Written)",
    "Big Data Analytics",
    "BIM (Building Information Modeling)",
    "Bioinformatics",
    "Biology",
    "Biostatistics",
    "Blender 3D",
    "Blockchain",
    "Blogging",
    "BMS modelling & simulation",
    "Bodo Proficiency(Spoken)",
    "Bodo Proficiency(Written)",
    "Bootstrap",
    "British English",
    "Business Analysis",
    "Business Research",
    "C Programming",
    "C#",
    "C#.NET",
    "C++ Programming",
    "CAD",
    "CakePHP",
    "Calligraphy",
    "CAM",
    "Canva",
    "Catalyst MVC Web Framework",
    "Catia",
    "CCNA",
    "Chemistry",
    "CI\/CD",
    "Cinema 4D",
    "Circuit Design",
    "Client interaction",
    "Client Relationship",
    "Clip Studio Paint",
    "CLO3D",
    "Cloud Computing",
    "Cloud Firestore",
    "CMS",
    "CNC",
    "CNC Programming",
    "CodeIgniter",
    "Colour Theory for Designers",
    "Compensation management",
    "Computational Neuroscience",
    "Computer Networking",
    "Computer Networks",
    "Computer Vision",
    "COMSOL",
    "Content Marketing",
    "Content Writing",
    "CONVERGE",
    "Copywriting",
    "CorelDRAW",
    "Creative Writing",
    "CRM",
    "CSS",
    "Culinary Arts",
    "Dancer MVC Web Framework",
    "Dart",
    "Data Analysis",
    "Data Analytics",
    "Data Science",
    "Data Structures",
    "Database Management System (DBMS)",
    "Database Testing",
    "DBIx Class",
    "Deep Learning",
    "Deluge",
    "Design Thinking",
    "DevOps",
    "Dietetics\/Nutrition",
    "Digital Advertising",
    "Digital Art",
    "Digital Marketing",
    "Digital Signal Processing",
    "DigitalOcean",
    "Display Advertising",
    "Distributed Computing",
    "Django",
    "Docker",
    "Docker Products",
    "Dogri Proficiency(Spoken)",
    "Dogri Proficiency(Written)",
    "Draping",
    "Drupal",
    "EAGLE",
    "Eclipse (IDE)",
    "Econometrics",
    "Economics",
    "Effective Communication",
    "Elasticsearch",
    "ElectronJS",
    "Email Marketing",
    "Embedded Systems",
    "Ember.js",
    "Embroidery making",
    "Employment engagement",
    "Engineering Drawing",
    "Engineering Surveying",
    "English Proficiency (Spoken)",
    "English Proficiency (Written)",
    "Enterprise Resource Planning(ERP)",
    "ERDAS Imagine",
    "ERP Implementation and Deployment",
    "Estimation (estimating)",
    "Ethereum",
    "Ethical Hacking",
    "Event Management",
    "EViews",
    "Express.js",
    "Eyeon Fusion",
    "Facebook Ads",
    "Facebook Marketing",
    "Fashion Designing",
    "Fashion Styling",
    "FastAPI",
    "Figma",
    "Final Cut Pro",
    "Financial literacy",
    "Financial Modeling",
    "Firebase",
    "Firebase Cloud Messaging",
    "FL Studio (formerly known as FruityLoops)",
    "Flask",
    "Flutter",
    "FPGA Synthesis and Prototyping",
    "French Proficiency (spoken)",
    "French Proficiency (written)",
    "Gazebo",
    "German Proficiency (Spoken)",
    "German Proficiency (Written)",
    "GIMP",
    "Git",
    "Git Bash",
    "Git SVN",
    "GitHub",
    "Gitlab",
    "GNU Octave",
    "Golang",
    "Google AdWords",
    "Google Analytics",
    "Google Cloud Computing",
    "Google SketchUp ",
    "Google Suite (G Suite)",
    "Google Workspace",
    "GraphQL",
    "GUI Testing",
    "Guitar",
    "Gujarati Proficiency (Spoken)",
    "Gujarati Proficiency (Written)",
    "Hadoop",
    "Hasura",
    "HelioScope",
    "Heroku",
    "Hibernate (Java)",
    "Hindi Proficiency (Spoken)",
    "Hindi Proficiency (Written)",
    "History",
    "Holiday Package Design",
    "HR Analytics",
    "HR branding",
    "HRIS",
    "HTML",
    "HTML&CSS",
    "HubL",
    "Human Resource Information System (HRIS)",
    "Hyperledger",
    "HyperMesh",
    "Image Processing",
    "Immunological Techniques",
    "Industrial automation",
    "Information architecture",
    "Inkscape",
    "Instagram Marketing",
    "Integromat",
    "Internet of Things (IoT)",
    "Interpersonal skills",
    "InterPlanetary File System",
    "Investing",
    "Ionic",
    "iOS",
    "J2EE",
    "Jade",
    "Japanese Proficiency (Spoken)",
    "Japanese Proficiency (Written)",
    "Java",
    "JavaFX",
    "JavaScript",
    "Jenkins",
    "Jira",
    "Joomla",
    "jQuery",
    "JSON",
    "JSP",
    "Julia",
    "Kannada",
    "Kannada Proficiency (Spoken)",
    "Kannada Proficiency (Written)",
    "Kashmiri Proficiency (Spoken)",
    "Kashmiri Proficiency (written)",
    "KeyShot",
    "KeystoneJS",
    "Konkani Proficiency (Spoken)",
    "Konkani Proficiency (Written)",
    "Korean Proficiency (Spoken)",
    "Korean Proficiency (Written)",
    "Kotlin",
    "Krita",
    "Kubernetes",
    "Labour laws",
    "LabVIEW",
    "LARAVEL",
    "LaTeX",
    "Lead Generation",
    "LESS",
    "LibreOffice",
    "Libuntu",
    "Linear Programming",
    "LinkedIn Marketing",
    "Linux",
    "Lucene\/Solr",
    "Lucidchart",
    "Machine Learning",
    "Magento",
    "Malayalam",
    "Malayalam Proficiency (Spoken)",
    "Malayalam Proficiency (Written)",
    "Manipuri Proficiency (Spoken)",
    "Manipuri Proficiency (Written)",
    "Manpower Planning",
    "Manual Testing",
    "Map Study",
    "Marathi Proficiency(Spoken)",
    "Marathi Proficiency(Written)",
    "Market Analysis",
    "Market research",
    "Marketing",
    "Marketing Campaigns ",
    "Marketing Programs ",
    "Marketing Strategies ",
    "Materialize",
    "Mathematics",
    "MATLAB",
    "MEAN\/MERN Stack",
    "Meteor JS Framework",
    "Microbiological Techniques",
    "Microsoft Azure",
    "Microsoft PowerApps",
    "Microsoft Project",
    "Microsoft Visio",
    "Microsoft Visual Studio",
    "Minitab",
    "Model View Controller(MVC)",
    "Mojolicious MVC Web Framework",
    "Molecular Biology Techniques",
    "Molecular Medicine",
    "MongoDB",
    "Moodle",
    "Moose (Perl)",
    "MS SQL Server",
    "MS-Excel",
    "MS-Office",
    "MS-PowerPoint",
    "MS-Word",
    "Music",
    "MySQL",
    "Natural Language Processing (NLP)",
    "Negotiation & Problem-solving",
    "Nepali Proficiency(Spoken)",
    "Nepali Proficiency(Written)",
    "Neural Networks",
    "Next Generation Sequencing (NGS)",
    "Next.js",
    "Nginx",
    "NI Multisim",
    "Node.js",
    "NoSQL",
    "NX Siemens (formerly Unigraphics NX)",
    "OAuth",
    "Objective C",
    "Odia Proficiency(Spoken)",
    "Odia Proficiency(Written)",
    "Odoo",
    "Online Teaching",
    "OpenCart",
    "OpenCV",
    "OpenGL",
    "Operations",
    "Oracle",
    "OrCAD",
    "Painting",
    "Parallel Thinking",
    "Patran",
    "Pattern making",
    "PayPal API",
    "PCB Design",
    "PCB Soldering",
    "Performance Management System",
    "Perl",
    "Pharmacovigilance",
    "PhoneGap",
    "Photography",
    "PHP",
    "Physics",
    "Pinterest Marketing",
    "PLC Programming",
    "PLC SCADA",
    "PostgreSQL",
    "Postman",
    "Power BI",
    "Primavera",
    "Prioritization",
    "Problem Solving",
    "Product Lifecycle Management(PLM)",
    "Product Management",
    "Product Strategy",
    "Project Management",
    "Proofreading",
    "Prospecting",
    "Proteus Design Suite",
    "PROTOTYPING",
    "PTC Creo",
    "Pug",
    "Punjabi Proficiency (Spoken)",
    "Punjabi Proficiency (Written)",
    "PVsyst",
    "Python",
    "Quality Assurance\/Quality Control (QA\/QC)",
    "Quantity Survey (QS)",
    "QuarkXPress",
    "R Programming",
    "R Viz",
    "Rapid Prototyping",
    "Raspberry Pi",
    "React",
    "React Native",
    "Reaction Commerce",
    "ReactJS",
    "Reconnaissance Survey",
    "Recruitment",
    "Redis",
    "Redux",
    "Report Writing",
    "Research and Analytics",
    "Responsive Design",
    "REST API",
    "RETScreen",
    "Rhino",
    "Robot Operating System (ROS)",
    "Robotic Process Automation (RPA)",
    "Robotics",
    "Ruby on Rails",
    "Rust",
    "Salary structure",
    "Sales",
    "Sales pitch",
    "Salesforce",
    "Sanskrit Proficiency (spoken)",
    "Sanskrit Proficiency (written)",
    "Santali Proficiency(Spoken)",
    "Santali Proficiency(Written)",
    "SAP",
    "SAS",
    "Sass",
    "SCSS",
    "Search Engine Marketing (SEM)",
    "Search Engine Optimization (SEO)",
    "Selenium",
    "Servlets",
    "SharePoint",
    "Shell Scripting",
    "Simulink",
    "Sindhi Proficiency(Spoken)",
    "Sindhi Proficiency(Written)",
    "Six Sigma",
    "Sketch",
    "Sketching",
    "SOC",
    "Social Media Marketing",
    "Software Testing",
    "Solidity",
    "SolidWorks",
    "Sony Vegas Pro",
    "Spanish Proficiency(Spoken)",
    "Spanish Proficiency(Written)",
    "Spring MVC",
    "SPSS",
    "SQL",
    "SQLite",
    "STAAD.Pro",
    "Star CCM",
    "STAR-CCM+",
    "STATA",
    "Statistical Modeling",
    "Statistics",
    "Statutory compliances",
    "Stenography ",
    "Stock Trading",
    "Storyboarding",
    "Stripe Payment API",
    "Subject Matter Expert (SME)",
    "Substance Painter",
    "Swift",
    "Swing (Java)",
    "Symfony",
    "SYSTEM ADMINISTRATOR",
    "System Biology",
    "SystemVerilog",
    "Tableau",
    "Tailwind CSS",
    "Tally",
    "Tamil Proficiency (Spoken)",
    "Tamil Proficiency (Written)",
    "Teaching",
    "Telugu Proficiency (Spoken)",
    "Telugu Proficiency (Written)",
    "Terraform",
    "Time Management",
    "Training and Development",
    "Transcription",
    "Translation",
    "Travel Itinerary Making",
    "Truffle",
    "TypeScript",
    "UI & UX Design",
    "UiPath",
    "Underscore.js",
    "Unity 3D",
    "Unity Engine",
    "Unix",
    "Unreal Engine",
    "Urdu Proficiency(Spoken)",
    "Urdu Proficiency(Written)",
    "User Interface (UI) Development",
    "UVM",
    "UX Research",
    "Vagrant",
    "VAPT",
    "Vector Dynamics",
    "Verilog",
    "VHDL",
    "Video Editing",
    "Video Making",
    "Virtualization",
    "Visual Basic (VB)",
    "VLSI",
    "VMware",
    "Voice-over artist",
    "Voiceover",
    "VS Code",
    "Vue Js",
    "Web Application Security",
    "web3.js",
    "Webflow",
    "Windows Mobile Application Development",
    "Wireframing",
    "WordPress",
    "Xamarin",
    "Xcode",
    "XML",
    "Yii",
    "YouTube Ads",
    "ZBrush"
];

module.exports = { skills };